// AUTO-GENERATED by scripts/build-tokens.ts. Do not edit by hand.
// Source: tokens/base.json. Regenerate via `npm run tokens:build`.

export const radius = {
  "xs": "0.125rem",
  "sm": "0.2rem",
  "md": "0.325rem",
  "lg": "0.45rem",
  "xl": "0.7rem",
  "full": "9999px"
} as const;

// Consumed by Tailwind theme.extend.backgroundImage.
export const gradients = {
  "gradient-brand": "var(--gradient-brand)",
  "gradient-brand-r": "var(--gradient-brand-r)",
  "gradient-gold": "var(--gradient-gold)"
} as const;

export const fontFamily = {
  "sans": "'Inter', system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  "mono": "'JetBrains Mono', ui-monospace, SFMono-Regular, Menlo, monospace"
} as const;

export const typeScale = {
  "displayLarge": {
    "size": "3.5625rem",
    "lineHeight": "4rem",
    "weight": 400,
    "tracking": "-0.016em"
  },
  "displayMedium": {
    "size": "2.8125rem",
    "lineHeight": "3.25rem",
    "weight": 400,
    "tracking": "0em"
  },
  "displaySmall": {
    "size": "2.25rem",
    "lineHeight": "2.75rem",
    "weight": 400,
    "tracking": "0em"
  },
  "headlineLarge": {
    "size": "2rem",
    "lineHeight": "2.5rem",
    "weight": 600,
    "tracking": "0em"
  },
  "headlineMedium": {
    "size": "1.75rem",
    "lineHeight": "2.25rem",
    "weight": 600,
    "tracking": "0em"
  },
  "headlineSmall": {
    "size": "1.5rem",
    "lineHeight": "2rem",
    "weight": 600,
    "tracking": "0em"
  },
  "titleLarge": {
    "size": "1.375rem",
    "lineHeight": "1.75rem",
    "weight": 600,
    "tracking": "0em"
  },
  "titleMedium": {
    "size": "1rem",
    "lineHeight": "1.5rem",
    "weight": 600,
    "tracking": "0.009em"
  },
  "titleSmall": {
    "size": "0.875rem",
    "lineHeight": "1.25rem",
    "weight": 600,
    "tracking": "0.007em"
  },
  "bodyLarge": {
    "size": "1rem",
    "lineHeight": "1.5rem",
    "weight": 400,
    "tracking": "0.031em"
  },
  "bodyMedium": {
    "size": "0.875rem",
    "lineHeight": "1.25rem",
    "weight": 400,
    "tracking": "0.018em"
  },
  "bodySmall": {
    "size": "0.75rem",
    "lineHeight": "1rem",
    "weight": 400,
    "tracking": "0.033em"
  },
  "labelLarge": {
    "size": "0.875rem",
    "lineHeight": "1.25rem",
    "weight": 500,
    "tracking": "0.007em"
  },
  "labelMedium": {
    "size": "0.75rem",
    "lineHeight": "1rem",
    "weight": 500,
    "tracking": "0.042em"
  },
  "labelSmall": {
    "size": "0.6875rem",
    "lineHeight": "1rem",
    "weight": 500,
    "tracking": "0.045em"
  }
} as const;

export const elevation = {
  "level0": "none",
  "level1": "0 1px 2px 0 rgb(15 23 42 / 0.04)",
  "level2": "0 1px 3px 0 rgb(15 23 42 / 0.08), 0 1px 2px -1px rgb(15 23 42 / 0.08)",
  "level3": "0 4px 6px -1px rgb(15 23 42 / 0.08), 0 2px 4px -2px rgb(15 23 42 / 0.08)",
  "level4": "0 10px 15px -3px rgb(15 23 42 / 0.08), 0 4px 6px -4px rgb(15 23 42 / 0.08)",
  "level5": "0 20px 25px -5px rgb(15 23 42 / 0.1), 0 8px 10px -6px rgb(15 23 42 / 0.08)"
} as const;

// M3 color roles — consumed by Tailwind theme.extend.colors.
export const mColorRoles = {
  "primary": "hsl(var(--mcolor-primary))",
  "on-primary": "hsl(var(--mcolor-on-primary))",
  "primary-container": "hsl(var(--mcolor-primary-container))",
  "on-primary-container": "hsl(var(--mcolor-on-primary-container))",
  "secondary": "hsl(var(--mcolor-secondary))",
  "on-secondary": "hsl(var(--mcolor-on-secondary))",
  "secondary-container": "hsl(var(--mcolor-secondary-container))",
  "on-secondary-container": "hsl(var(--mcolor-on-secondary-container))",
  "tertiary": "hsl(var(--mcolor-tertiary))",
  "on-tertiary": "hsl(var(--mcolor-on-tertiary))",
  "tertiary-container": "hsl(var(--mcolor-tertiary-container))",
  "on-tertiary-container": "hsl(var(--mcolor-on-tertiary-container))",
  "error": "hsl(var(--mcolor-error))",
  "on-error": "hsl(var(--mcolor-on-error))",
  "error-container": "hsl(var(--mcolor-error-container))",
  "on-error-container": "hsl(var(--mcolor-on-error-container))",
  "background": "hsl(var(--mcolor-background))",
  "on-background": "hsl(var(--mcolor-on-background))",
  "surface": "hsl(var(--mcolor-surface))",
  "on-surface": "hsl(var(--mcolor-on-surface))",
  "surface-variant": "hsl(var(--mcolor-surface-variant))",
  "on-surface-variant": "hsl(var(--mcolor-on-surface-variant))",
  "surface-container-low": "hsl(var(--mcolor-surface-container-low))",
  "surface-container": "hsl(var(--mcolor-surface-container))",
  "surface-container-high": "hsl(var(--mcolor-surface-container-high))",
  "surface-container-highest": "hsl(var(--mcolor-surface-container-highest))",
  "outline": "hsl(var(--mcolor-outline))",
  "outline-variant": "hsl(var(--mcolor-outline-variant))"
} as const;
