#!/usr/bin/env tsx
/**
 * Transforms tokens/base.json into:
 *   - src/styles/tokens.css  (CSS custom properties, :root + .dark)
 *   - src/styles/tokens.ts   (consumed by tailwind.config.ts)
 *
 * Run via `npm run tokens:build`. Also runs after `npm run tokens:sync`.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

type ColorPair = { light: string; dark: string };
type TypeStyle = { size: string; lineHeight: string; weight: number; tracking: string };

interface Tokens {
  color: Record<string, ColorPair>;
  radius: Record<string, string>;
  typography: {
    fontFamily: Record<string, string>;
    scale: Record<string, TypeStyle>;
  };
  elevation: Record<string, string>;
}

// hex (#RRGGBB) → "H S% L%" triple string (shadcn/Tailwind expects space-separated HSL)
function hexToHslTriple(hex: string): string {
  const m = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex.trim());
  if (!m) throw new Error(`Invalid hex color: ${hex}`);
  const r = parseInt(m[1], 16) / 255;
  const g = parseInt(m[2], 16) / 255;
  const b = parseInt(m[3], 16) / 255;
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const l = (max + min) / 2;
  let h = 0;
  let s = 0;
  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r: h = ((g - b) / d + (g < b ? 6 : 0)) * 60; break;
      case g: h = ((b - r) / d + 2) * 60; break;
      case b: h = ((r - g) / d + 4) * 60; break;
    }
  }
  const H = Math.round(h * 10) / 10;
  const S = Math.round(s * 1000) / 10;
  const L = Math.round(l * 1000) / 10;
  return `${H} ${S}% ${L}%`;
}

// camelCase → kebab-case
const kebab = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

// Map M3 role → shadcn-compat CSS var alias. Keeps existing shadcn components working.
const SHADCN_ALIAS: Record<string, keyof Tokens["color"]> = {
  background: "surface",
  foreground: "onSurface",
  card: "surface",
  "card-foreground": "onSurface",
  popover: "surfaceContainerLow",
  "popover-foreground": "onSurface",
  primary: "primary",
  "primary-foreground": "onPrimary",
  secondary: "secondaryContainer",
  "secondary-foreground": "onSecondaryContainer",
  muted: "surfaceVariant",
  "muted-foreground": "onSurfaceVariant",
  accent: "primaryContainer",
  "accent-foreground": "onPrimaryContainer",
  destructive: "error",
  "destructive-foreground": "onError",
  border: "outlineVariant",
  input: "outline",
  ring: "primary",
};

function buildCss(tokens: Tokens): string {
  const lines: string[] = [];
  lines.push("/* AUTO-GENERATED by scripts/build-tokens.ts. Do not edit by hand. */");
  lines.push("/* Source: tokens/base.json. Regenerate via `npm run tokens:build`. */");
  lines.push("");

  const emitColorBlock = (mode: "light" | "dark") => {
    const out: string[] = [];
    // M3 role vars
    for (const [name, pair] of Object.entries(tokens.color)) {
      out.push(`  --mcolor-${kebab(name)}: ${hexToHslTriple(pair[mode])};`);
    }
    // shadcn aliases
    for (const [alias, role] of Object.entries(SHADCN_ALIAS)) {
      const pair = tokens.color[role];
      out.push(`  --${alias}: ${hexToHslTriple(pair[mode])};`);
    }
    return out.join("\n");
  };

  lines.push("@layer base {");
  lines.push("  :root {");
  lines.push(emitColorBlock("light"));
  // radius
  for (const [name, val] of Object.entries(tokens.radius)) {
    lines.push(`    --radius-${name}: ${val};`);
  }
  // backwards-compat — shadcn components reference --radius directly
  lines.push(`    --radius: ${tokens.radius.md};`);
  // elevation
  for (const [name, val] of Object.entries(tokens.elevation)) {
    lines.push(`    --elevation-${name}: ${val};`);
  }
  // font families
  for (const [name, val] of Object.entries(tokens.typography.fontFamily)) {
    lines.push(`    --font-${name}: ${val};`);
  }
  lines.push("  }");
  lines.push("");
  lines.push("  .dark {");
  lines.push(emitColorBlock("dark"));
  lines.push("  }");
  lines.push("}");
  lines.push("");
  // typography utility classes
  lines.push("@layer base {");
  for (const [name, style] of Object.entries(tokens.typography.scale)) {
    lines.push(`  .text-${kebab(name)} {`);
    lines.push(`    font-size: ${style.size};`);
    lines.push(`    line-height: ${style.lineHeight};`);
    lines.push(`    font-weight: ${style.weight};`);
    lines.push(`    letter-spacing: ${style.tracking};`);
    lines.push(`  }`);
  }
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

function buildTs(tokens: Tokens): string {
  // Emit kebab-case keys so Tailwind class names read as `bg-m-primary-container`.
  const mColorRoles = Object.fromEntries(
    Object.keys(tokens.color).map((role) => [kebab(role), `hsl(var(--mcolor-${kebab(role)}))`])
  );
  return [
    "// AUTO-GENERATED by scripts/build-tokens.ts. Do not edit by hand.",
    "// Source: tokens/base.json. Regenerate via `npm run tokens:build`.",
    "",
    `export const radius = ${JSON.stringify(tokens.radius, null, 2)} as const;`,
    "",
    `export const fontFamily = ${JSON.stringify(tokens.typography.fontFamily, null, 2)} as const;`,
    "",
    `export const typeScale = ${JSON.stringify(tokens.typography.scale, null, 2)} as const;`,
    "",
    `export const elevation = ${JSON.stringify(tokens.elevation, null, 2)} as const;`,
    "",
    "// M3 color roles — consumed by Tailwind theme.extend.colors.",
    `export const mColorRoles = ${JSON.stringify(mColorRoles, null, 2)} as const;`,
    "",
  ].join("\n");
}

function main() {
  const src = resolve(root, "tokens/base.json");
  const raw = readFileSync(src, "utf8");
  const tokens = JSON.parse(raw) as Tokens;

  const cssOut = resolve(root, "src/styles/tokens.css");
  const tsOut = resolve(root, "src/styles/tokens.ts");
  mkdirSync(dirname(cssOut), { recursive: true });

  writeFileSync(cssOut, buildCss(tokens));
  writeFileSync(tsOut, buildTs(tokens));

  console.log(`[tokens] wrote ${cssOut}`);
  console.log(`[tokens] wrote ${tsOut}`);
}

main();
