#!/usr/bin/env tsx
/**
 * Reads data/service_catalog.csv and writes supabase/seed_services.sql —
 * a single SQL statement that inserts every service row and wires up its rule_id.
 * Idempotent on re-run: uses `on conflict (code) do update`.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import Papa from "papaparse";

type CsvRow = {
  ServiceID: string;
  ServiceName: string;
  CurrentSellPrice: string;
  PricingModel: string;
  UnitOfSale: string;
  ScopeDefinition: string;
  IncludedRevisionsLimits: string;
  TriggerToStartWork: string;
  CompletionDefinition: string;
  OwnerRole: string;
  Status: string;
  Notes: string;
  Genre: string;
};

const pricingModelMap: Record<string, string> = {
  Hourly: "hourly",
  "Fixed Price": "fixed",
  Percentage: "percentage",
};

function sqlString(v: string | null | undefined): string {
  if (v == null || v === "") return "null";
  return `'${v.replace(/'/g, "''")}'`;
}

const csvPath = resolve("data/service_catalog.csv");
const csv = readFileSync(csvPath, "utf8");

const parsed = Papa.parse<CsvRow>(csv, {
  header: true,
  skipEmptyLines: true,
});

if (parsed.errors.length > 0) {
  console.error("CSV parse errors:", parsed.errors);
  process.exit(1);
}

const rows = parsed.data.filter((r) => r.ServiceID && r.ServiceName);

const tuples = rows.map((r) => {
  const pricingModel = pricingModelMap[r.PricingModel] ?? "fixed";
  const priceRaw = Number(r.CurrentSellPrice || "0");
  const isPercentage = pricingModel === "percentage";
  const sellPriceCents = isPercentage ? 0 : Math.round(priceRaw * 100);
  const percentageValue = isPercentage ? priceRaw : null;
  const status = (r.Status || "active").toLowerCase();

  return `  (${[
    sqlString(r.ServiceID),
    sqlString(r.ServiceName),
    String(sellPriceCents),
    sqlString(pricingModel),
    sqlString(r.UnitOfSale),
    percentageValue != null ? String(percentageValue) : "null",
    sqlString(r.Genre),
    sqlString(r.ScopeDefinition),
    sqlString(r.IncludedRevisionsLimits),
    sqlString(r.TriggerToStartWork),
    sqlString(r.CompletionDefinition),
    sqlString(r.OwnerRole),
    sqlString(status === "active" ? "active" : "draft"),
    sqlString(r.Notes),
  ].join(", ")})`;
});

const sql = `-- Auto-generated by scripts/generate-seed.ts. Do not hand-edit.
-- Inserts ${rows.length} services, looking up rule_id by Genre name.
-- Re-runnable: updates existing rows matched by code.

with src (code, name, sell_price_cents, pricing_model, unit_of_sale, percentage_value, genre, scope_definition, included_revisions, trigger_to_start, completion_definition, owner_role, status, notes) as (
  values
${tuples.join(",\n")}
)
insert into public.services
  (code, name, sell_price_cents, pricing_model, unit_of_sale, percentage_value, rule_id, scope_definition, included_revisions, trigger_to_start, completion_definition, owner_role, status, notes)
select
  s.code,
  s.name,
  s.sell_price_cents::int,
  s.pricing_model,
  s.unit_of_sale,
  s.percentage_value::numeric(5,2),
  r.id,
  s.scope_definition,
  s.included_revisions,
  s.trigger_to_start,
  s.completion_definition,
  s.owner_role,
  s.status,
  s.notes
from src s
left join public.rules r on r.name = s.genre
on conflict (code) do update set
  name = excluded.name,
  sell_price_cents = excluded.sell_price_cents,
  pricing_model = excluded.pricing_model,
  unit_of_sale = excluded.unit_of_sale,
  percentage_value = excluded.percentage_value,
  rule_id = excluded.rule_id,
  scope_definition = excluded.scope_definition,
  included_revisions = excluded.included_revisions,
  trigger_to_start = excluded.trigger_to_start,
  completion_definition = excluded.completion_definition,
  owner_role = excluded.owner_role,
  status = excluded.status,
  notes = excluded.notes;
`;

const outPath = resolve("supabase/seed_services.sql");
writeFileSync(outPath, sql);
console.error(`Wrote ${rows.length} services to ${outPath}`);
