-- 0023_brief_threading.sql
-- Apply via mcp__cc-supabase__apply_migration (name: brief_threading)
-- Phase 1 of Inbox v2: per-message threading + Apps Script relay infrastructure.

-- 1. Extend brief_source enum.
alter type public.brief_source add value if not exists 'gmail_relay';

-- 2. brief_messages — one row per Gmail message OR internal note.
create table public.brief_messages (
  id                 uuid primary key default gen_random_uuid(),
  brief_id           uuid not null references public.briefs(id) on delete cascade,
  gmail_message_id   text not null unique,
  direction          text not null check (direction in ('inbound','outbound','note')),
  from_email         text,
  from_name          text,
  to_emails          text[] not null default '{}',
  cc_emails          text[] not null default '{}',
  subject            text,
  body_text          text,
  body_html          text,
  attachments        jsonb not null default '[]',
  sent_at            timestamptz not null,
  relayed_by         text,
  created_at         timestamptz not null default now()
);
create index brief_messages_brief_idx on public.brief_messages (brief_id, sent_at);

-- 3. Add UNIQUE constraint on briefs.gmail_thread_id (existing column, no
-- constraint until now). Use a generated column so partial writes that omit
-- gmail_thread_id (manual briefs) don't trip the unique index.
alter table public.briefs
  add column gmail_thread_id_unique text unique
    generated always as (gmail_thread_id) stored;

-- 4. Per-thread aggregates maintained by the gmail-relay function.
alter table public.briefs
  add column last_message_at timestamptz,
  add column message_count int not null default 0;

-- 5. relay_secrets — per-teammate Apps Script tokens (plaintext; an API key
--    rather than a user-chosen password — same threat model as CLICKUP_PAT
--    stored as a Supabase secret).
create table public.relay_secrets (
  id          uuid primary key default gen_random_uuid(),
  user_email  text not null unique,
  secret      text not null,
  created_at  timestamptz not null default now(),
  revoked_at  timestamptz
);

comment on table public.brief_messages is
  'One row per Gmail message OR internal note belonging to a brief. Synthetic note ids use the form note-<uuid>.';
comment on column public.briefs.gmail_thread_id_unique is
  'Generated mirror of gmail_thread_id with UNIQUE constraint. Lets gmail-relay upsert idempotently.';
comment on table public.relay_secrets is
  'Per-teammate plaintext relay tokens used by gmail-relay to HMAC-verify request bodies. Random 32-byte tokens, generated by issue-relay-token, regeneratable.';
