-- 0082_placement_tasks.sql
-- Per-quote-line task breakdown: task × department × time × sprint points.
-- One row per task under a billable brief_task_sow_placements line. Generated by
-- intake (future), reviewed/edited by the ops manager (Stage 3), and the source
-- for ClickUp scheduling (future). No RLS — mirrors brief_task_sow_placements.

create table if not exists public.placement_tasks (
  id                uuid primary key default gen_random_uuid(),
  brief_id          uuid not null references public.briefs(id) on delete cascade,
  placement_id      uuid not null references public.brief_task_sow_placements(id) on delete cascade,
  title             text not null default '',
  department_id     uuid references public.departments(id),
  hours             numeric(6,2) not null default 0,
  points            numeric(7,2) not null default 0,
  -- true once the ops manager edits points directly — stops auto-reseed from hours.
  points_overridden boolean not null default false,
  sort_order        int not null default 0,
  ai_generated      boolean not null default false,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create index if not exists placement_tasks_brief_idx on public.placement_tasks(brief_id);
create index if not exists placement_tasks_placement_idx on public.placement_tasks(placement_id);

create or replace function public.placement_tasks_updated_at() returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists placement_tasks_updated_at on public.placement_tasks;
create trigger placement_tasks_updated_at
  before update on public.placement_tasks
  for each row execute function public.placement_tasks_updated_at();

comment on table public.placement_tasks is
  'Per-quote-line task breakdown (task × department × hours × sprint points). Ops-reviewed in the brief Task Breakdown stage; feeds ClickUp scheduling.';
